const experiencedata = [
  {"id":"recAGJfiU4CeaV0HL","order":1,"title":"Developer","dates":"04/2021 - Present","duties":["I am working on building new features and maintain a mobile and web app called BeeSecure (app.beesecure.ca) using Flutter and Codeigniter.","I have also developed rivercityinnovations.ca and an e-commerce website beesecure.ca with Wordpress.","I built and deployed a tcp server using node.js for receiving data from RCI trackers and send those to BeeSecure App.","I am responsible for designing & maintaining large-scale database.","I work on designing & developing RESTFul APIs."],"company":"Rivercity Innovations Ltd."},
  {"id":"recAGJfiU4CeaV0HL","order":2,"title":"Sessional Lecturer","dates":"09/2020 - 12/2020","duties":["I was a sessional lecturer of the Software Engineering Methodology Course.","Prepared and delivered lectures.", "Prepared assignments and final exam questions and answers.","Mentored 14 groups of students to develop amazing web, desktop, and mobile applications."],"company":"University of Regina","dept":"Computer Science"},
  {"id":"recIL6mJNfWObonls","order":3,"title":"Teaching Assistant","dates":"09/2018 - 12/2020","duties":["Courses that I work as a teaching assistant include  Algorithm Design & Analysis, Discrete Mathematics, Computer Networks, Computability & Formal Language, Programming & Problem Solving.","Prepared assignments answer scripts."," Evaluate assignments and midterms.", "Invigilate exams."],"company":"University of Regina","dept":"Computer Science"},
  {"id":"recIL6mJNfWObonlq","order":4,"title":"Research Assistant","dates":"09/2018 - 12/2020","duties":["Worked as a research assistant under the supervision of Professor Dr. Boting Yang.", "Worked on Combinatorial optimization and Algorithm optimization research projects.","Publish important findings in conferences and journals."],"company":"University of Regina", "dept":"Computer Science"},
  {"id":"rec61x18GVY99hQq5","order":5,"title":"Lecturer","dates":"04/2017 - 08/2018","duties":["Took various levels of undergraduate courses and sessional labs.","Supervised undergraduate thesis students.", "Arranged programming competitions and seminars.","Administrative works with the CS department."],"company":"Chittagong University of Engineering & Technology","dept":"Computer Science"},
  {"id":"rec61x18GVY99hQq6","order":6,"title":"Lecturer","dates":"05/2016 - 03/2017","duties":["Took various levels of undergraduate courses and sessional labs.","Supervised undergraduate students' projects.", "Carried out various research related to IoT and Neural Network."],"company":"Daffodil International University","dept":"Computer Science"}
];

export default experiencedata;